services:
  nodesight:
    extends:
      file: monitoring/monitoring.yml
      service: nodesight
    environment:
      HOSTNAME: ${NOTOS_HOSTNAME}
      ENABLE_STATS_API: true
      STATS_API_URL: ${STATS_API_URL}
      SERVER_PORT: ${NOTOS_NODESIGHT_PORT}
    annotations:
      traefik-ports: NOTOS_NODESIGHT_PORT
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:${NOTOS_NODESIGHT_PORT} || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dozzle:
    extends:
      file: monitoring/monitoring.yml
      service: dozzle
    ports:
      - ${NOTOS_DOZZLE_PORT}:8080
    annotations:
      traefik-ports: NOTOS_DOZZLE_PORT

  watchtower:
    extends:
      file: monitoring/monitoring.yml
      service: watchtower
