version: "3.8"

services:
  samba:
    container_name: samba
    restart: unless-stopped
    image: dperson/samba
    environment:
      - USERID=1000
      - GROUPID=1000
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    command: '-W -s "Share;/share;yes;no;no" -u "${SMB_USER};${SMB_PWD}"'
