.docker-template: &docker-template
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u mgarnier11 -p $DOCKER_HUB_TOKEN
    - docker buildx create --use

stages:
  - build
  - publish

build amd64:
  stage: build
  extends: .docker-template
  tags:
    - amd64
  script:
    - docker buildx build -f docker/Dockerfile --platform linux/amd64 -t mgarnier11/orchestrator:amd64 .

build arm64:
  stage: build
  extends: .docker-template
  tags:
    - arm64
  script:
    - docker buildx build -f docker/Dockerfile --platform linux/arm64 -t mgarnier11/orchestrator:arm64 .

publish:
  extends: .docker-template
  stage: publish
  needs:
    - build amd64
    - build arm64
  script:
    - docker buildx imagetools create --tag mgarnier11/orchestrator:latest mgarnier11/orchestrator:amd64 mgarnier11/orchestrator:arm64
