version: "3.8"

x-placement_apollon: &placement_apollon
  placement:
    constraints:
      - node.hostname == Apollon

services:
  autosaver:
    image: mgarnier11/autosaver
    volumes:
      - docker_data:/usr/app/backups/docker-data
      - athena_plex_config:/usr/app/backups/plex-config
      - athena_satisfactory_backups:/usr/app/backups/satisfactory/backups
      - athena_satisfactory_saved:/usr/app/backups/satisfactory/saved
      - athena_nextcloud:/usr/app/backups/nextcloud-datas
      - athena_minecraft:/usr/app/backups/minecraft
    environment:
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - UPTOBOX_TOKEN=${UPTOBOX_TOKEN}
      - CRON_SCHEDULE=15 4 * * *
    networks:
      - traefik-net
    deploy:
      <<: *placement_apollon
      labels:
        - traefik.enable=true
        - traefik.http.routers.{.Hostname}_autosaver.rule=Host(`autosaver.${HOME}`)
        - traefik.http.routers.{.Hostname}_autosaver.entrypoints=http
        - traefik.http.services.{.Hostname}_autosaver.loadbalancer.server.port=3000

networks:
  traefik-net:
    external: true

x-o: &o
  o: "rw,username=${SMB_USER},password=${SMB_PWD},iocharset=utf8,uid=1000,sec=ntlmv2,file_mode=0777,dir_mode=0777"

volumes:
  docker_data:
    driver: local
    driver_opts:
      type: cifs
      device: ${DOCKER_DATA}
      <<: *o
  athena_plex_config:
    driver: local
    driver_opts:
      type: cifs
      device: //${ATHENA_IP}/share/ssd-1/plex
      <<: *o
  athena_satisfactory_backups:
    driver: local
    driver_opts:
      type: cifs
      device: //${ATHENA_IP}/share/ssd-1/satisfactory/backups
      <<: *o
  athena_satisfactory_saved:
    driver: local
    driver_opts:
      type: cifs
      device: //${ATHENA_IP}/share/ssd-1/satisfactory/saved
      <<: *o
  athena_nextcloud:
    driver: local
    driver_opts:
      type: cifs
      device: //${ATHENA_IP}/share/hdd-1/nextcloud
      <<: *o
  athena_minecraft:
    driver: local
    driver_opts:
      type: cifs
      device: //${ATHENA_IP}/share/ssd-1/minecraft
      <<: *o
