version: "3.8"

x-placement_apollon: &placement_apollon
  placement:
    constraints:
      - node.hostname == Apollon

x-placement_athena: &placement_athena
  placement:
    constraints:
      - node.hostname == Athena

x-placement_hermes: &placement_hermes
  placement:
    constraints:
      - node.hostname == Hermes

services:
  glances:
    image: mgarnier11/my-glances
    # ports:
    #   - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /dev/sda1:/dev/sda1:ro
      # - /dev/sdb1:/dev/sdb1:ro
      # - /dev/sdc1:/dev/sdc1:ro
      # - /dev/sdd1:/dev/sdd1:ro
      # - /dev/nvme0n1:/dev/nvme0n1:ro
    environment:
      - GLANCES_OPT=-d -t 1 -w
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - traefik-net
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.{.Hostname}_glances.rule=Host(`glances.${HOME}`)
        - traefik.http.routers.{.Hostname}_glances.entrypoints=http
        - traefik.http.services.{.Hostname}_glances.loadbalancer.server.port=61208

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.{.Hostname}_dozzle.rule=Host(`dozzle.${HOME}`)
        - traefik.http.routers.{.Hostname}_dozzle.entrypoints=http
        - traefik.http.services.{.Hostname}_dozzle.loadbalancer.server.port=8080

  apollon_dashy:
    image: mgarnier11/my-dashy
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    volumes:
      - dashy_config:/app/public
    networks:
      - traefik-net
    dns:
      - ${HERMES_IP}
    deploy:
      <<: *placement_apollon
      labels:
        - traefik.enable=true
        - traefik.http.routers.apollon_dashy.rule=Host(`dashy.${HOME}`)
        - traefik.http.routers.apollon_dashy.entrypoints=http
        - traefik.http.services.apollon_dashy.loadbalancer.server.port=80

  # shepherd:
  #   image: mazzolino/shepherd
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   deploy:
  #     <<: *placement_apollon

networks:
  traefik-net:
    external: true

x-freebox_opts: &freebox_opts
  type: cifs
  # device: //192.168.0.254/SSD1/docker-data
  o: "rw,username=${SMB_USER},password=${SMB_PWD},iocharset=utf8,uid=1000,sec=ntlmv2,file_mode=0777,dir_mode=0777"

volumes:
  dashy_config:
    driver: local
    driver_opts:
      <<: *freebox_opts
      device: ${DOCKER_DATA}/dashy
