version: "3.8"

services:
  nextcloud_db:
    container_name: nexcloud_db
    restart: unless-stopped
    image: mariadb:10.5
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - nextcloud-net
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWD} # Requested, set the root's password of MySQL service.
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_LOG_CONSOLE=true
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: nextcloud:latest
    volumes:
      - /hdd-1/nextcloud/data:/data
      - nextcloud_config:/var/www/html/config
    networks:
      - nextcloud-net
    ports:
      - ${ATHENA_NEXTCLOUD_PORT}:80
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    user: 1000:1000
    depends_on:
      - nextcloud_db
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_HOST=nextcloud_db:3306
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_URL}
      - TRUSTED_PROXIES=51.77.195.239
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_URL}
      - OVERWRITEWEBROOT=/
      - OVERWRITECONDADDR=^
      - OVERWRITECLIURL=https://${NEXTCLOUD_URL}

networks:
  nextcloud-net:
