services:
  # file_server:
  #   container_name: file_server
  #   restart: unless-stopped
  #   image: halverneus/static-file-server
  #   volumes:
  #     - /big-hdd/shared-files:/web
  #   ports:
  #     - ${ATHENA_FILE_SERVER_PORT}:8080
