version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home_assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - ${EUROS_HOME_ASSISTANT_PORT}:8123
    annotations:
      traefik-ports: EUROS_HOME_ASSISTANT_PORT
