- name: Sync compose folder
  ansible.builtin.synchronize:
    src: "{{ lookup('env', 'COMPOSE_DIR') | default(playbook_dir + '/../../compose/', true) }}/"
    dest: '{{ compose_dest }}'
    delete: true

- name: Run compose command for {{stack}}
  when: stack is defined
  ansible.builtin.include_tasks: tasks/cmp.yml
  vars:
    stack_name: '{{ stack }}'
