- name: Sync compose folder
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/../../compose/"
    dest: "{{ compose_dest }}/"
    delete: true

- name: Find all stacks under the compose folder
  ansible.builtin.find:
    paths: "{{ compose_dest }}"
    file_type: directory
    recurse: false
  register: stack_folders

- name: Run compose on {{stack}} on all hosts
  when: stack is defined
  ansible.builtin.include_tasks: tasks/cmp.yml
  vars:
    stack_name: "{{ stack }}"
