name: media

services:
  jellyfin:
    container_name: jellyfin
    restart: unless-stopped
    image: jellyfin/jellyfin
    ports:
      - ${ATHENA_MEDIA_VIDEO_PORT}:8096
    labels:
      - traefik-conf.port=$ATHENA_MEDIA_VIDEO_PORT
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - NVIDIA_VISIBLE_DEVICES=all
      - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - /ssd-1/jellyfin/config:/config
      - /ssd-1/jellyfin/cache:/cache
      - /big-hdd/media:/media
    runtime: nvidia
    healthcheck:
      test: curl -f http://localhost:8096 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  gonic-music:
    image: sentriz/gonic:v0.16.0
    container_name: gonic_music
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      # optionally, see more available env vars in the readme
    ports:
      - ${ATHENA_MEDIA_MUSIC_PORT}:80
    labels:
      - traefik-conf.port=$ATHENA_MEDIA_MUSIC_PORT
      - traefik-conf.name=music
    volumes:
      - /ssd-1/gonic/music/data:/data
      - /ssd-1/gonic/music/cache:/cache # transcode / covers / etc cache dir
      - /ssd-1/gonic/music/podcasts:/podcasts # your podcasts
      - /ssd-1/gonic/music/playlists:/playlists # your playlists
      - /big-hdd/media/musics:/music:ro # your music
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:80/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  gonic-sagas:
    image: sentriz/gonic:v0.16.0
    container_name: gonic_sagas
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      # optionally, see more available env vars in the readme
    ports:
      - ${ATHENA_MEDIA_SAGAS_PORT}:80
    labels:
      - traefik-conf.port=$ATHENA_MEDIA_SAGAS_PORT
      - traefik-conf.name=sagas
    volumes:
      - /ssd-1/gonic/sagas/data:/data
      - /ssd-1/gonic/sagas/cache:/cache # transcode / covers / etc cache dir
      - /ssd-1/gonic/sagas/podcasts:/podcasts # your podcasts
      - /ssd-1/gonic/sagas/playlists:/playlists # your playlists
      - /big-hdd/media/sagas-mp3:/music:ro # your music
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:80/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  airsonic:
    image: tamland/airsonic-refix:latest
    container_name: airsonic
    restart: unless-stopped
    ports:
      - ${ATHENA_AIRSONIC_PORT}:80
    labels:
      - traefik-conf.port=ATHENA_AIRSONIC_PORT
    healthcheck:
      test: curl -f http://localhost
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
