name: backup

services:
  autosaver:
    container_name: autosaver
    restart: unless-stopped
    image: mgarnier11/autosaver
    volumes:
      - /docker-data/home_assistant:/backups/home_assistant-config
      - /docker-data/influxdb:/backups/influxdb-data
      - type: volume
        source: fbx_docker_data
        target: /config
        volume:
          subpath: autosaver
    ports:
      - ${ZEPHYR_AUTOSAVER_PORT}:3000
    labels:
      - traefik-conf.port=${ZEPHYR_AUTOSAVER_PORT}
      - traefik-conf.rule=Host(`autosaver.zephyr.${PUBLIC_DOMAIN_NAME}`)
    privileged: true
    environment:
      - CRON_SCHEDULE=15 4 * * *
      - BACKUP_CONFIG_PATH=/config/config-zephyr.yml
      - NTFY_SERVER=${NTFY_SERVER}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - ARCHIVE_API_TYPE=zip
      # - LOG_LEVEL=5
