version: "3.8"

services:
  node-proxy:
    image: mgarnier11/node-proxy
    container_name: node-proxy
    restart: unless-stopped
    network_mode: host
    environment:
      - AUTO_RELOAD_CONFIG=true
      - CONFIG_FILE=/config/config.json
    volumes:
      - node_proxy_config:/config