version: "3.8"

services:
  jellyfin:
    container_name: jellyfin
    restart: unless-stopped
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - ${ATHENA_JELLYFIN_PORT}:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - NVIDIA_VISIBLE_DEVICES=all
      - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - /ssd-1/jellyfin/config:/config
      - /ssd-1/jellyfin/cache:/cache
      - /big-hdd/plex:/media
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
