name: bitwarden

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - ${APOLLON_BITWARDEN_PORT}:80
    volumes:
      - type: volume
        source: fbx_docker_data
        target: /data
        volume:
          subpath: bitwarden
    labels:
      - traefik-conf.port=${APOLLON_BITWARDEN_PORT}
      - my-traefik.http.routers.apollon_bitwarden_cert.rule=Host(`bitwarden.${PUBLIC_DOMAIN_NAME}.nf`)
      - my-traefik.http.routers.apollon_bitwarden_cert.service=apollon_bitwarden
      - my-traefik.http.routers.apollon_bitwarden_cert.entrypoints=https
      - my-traefik.http.routers.apollon_bitwarden_cert.tls.certResolver=tls-resolver
      - my-traefik.http.routers.apollon_bitwarden_cert.tls.options=ca-mgarnier11@file
