version: "3.8"

services:
  adguard:
    container_name: adguard
    restart: unless-stopped
    image: adguard/adguardhome
    volumes:
      - adguard_conf:/opt/adguardhome/conf
      - adguard_data:/opt/adguardhome/work
    ports:
      - ${HERMES_IP}:53:53/tcp
      - ${HERMES_IP}:53:53/udp
      - ${HERMES_ADGUARD_PORT}:3000/tcp
    annotations:
      traefik-ports: HERMES_ADGUARD_PORT
