services:
  minecraft:
    container_name: minecraft
    restart: unless-stopped
    image: itzg/minecraft-server
    ports:
      - ${ATHENA_MINECRAFT_PORT}:25565
      - ${ATHENA_MINECRAFT_DYNMAP_PORT}:8123 # Dynmap
    volumes:
      - /ssd-1/minecraft/modded-1.19.2:/data
    environment:
      - EULA=TRUE
      - VERSION=1.19.2
      - MEMORY=12G
      - MOTD=MG MC Server
      - OVERRIDE_SERVER_PROPERTIES=TRUE
      - TYPE=FORGE
      - FORGE_VERSION=43.2.21
      # - RCON_PASSWORD=${MINECRAFT_RCON_PASSWORD}
