- name: Check if firewalld is intalled
  become: true
  ansible.builtin.command: firewalld --version
  register: firewalld_version
  ignore_errors: true
  changed_when: true

- name: Install firewalld
  when: firewalld_version.rc != 0
  block:
    - name: Install firewalld
      become: true
      ansible.builtin.apt:
        pkg:
          - firewalld
        state: present
        update_cache: true

    - name: Start firewalld
      become: true
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
