# - name: Install firewalld
#   become: true
#   ansible.builtin.apt:
#     pkg:
#       - firewalld
#     state: present
#     update_cache: true

# - name: Allow ports 80 443 and 4269
#   become: true
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: enabled
#     immediate: true
#   with_items:
#     - 80/tcp
#     - 443/tcp
#     - 4269/tcp

# - name: Start firewalld
#   become: true
#   ansible.builtin.systemd:
#     name: firewalld
#     state: started
#     enabled: true
