- name: My first play
  hosts: myhosts
  gather_facts: false
  pre_tasks:
    - name: checking limit arg
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true
    - name: Find all stacks under the compose folder # noqa: run-once[task]
      ansible.builtin.find:
        paths: '{{ playbook_dir }}/../compose'
        file_type: directory
        recurse: false
      register: stack_folders
      delegate_to: localhost
      run_once: true
    - name: Set stack names # noqa: run-once[task]
      ansible.builtin.set_fact:
        stack_names: "{{ stack_folders.files | map(attribute='path') | map('basename') | list }}"
      run_once: true
  tasks:
    - name: Sync compose folder
      ansible.builtin.synchronize:
        src: '{{ playbook_dir }}/../compose/'
        dest: '{{ compose_dest }}/'
        delete: true

    - name: Loop over stack names and run compose
      when: stack is undefined
      ansible.builtin.include_tasks: tasks/cmp.yml
      vars:
        stack_name: '{{ item }}'
      loop: '{{ stack_names }}'
      loop_control:
        loop_var: stack_name

    - name: Run compose for {{stack}}
      ansible.builtin.include_tasks: tasks/cmp.yml
      vars:
        stack_name: '{{ stack }}'
      when: stack is defined

    # - name: Loop over stack names and run down
    #   ansible.builtin.include_tasks: tasks/cmp.yml
    #   vars:
    #     stack_name: '{{ item }}'
    #     action_name: 'down'
    #   loop: '{{ stack_names }}'
    #   loop_control:
    #     loop_var: stack_name
