- name: Fresh install
  hosts: myhosts
  pre_tasks:
    - name: Load installation variables
      ansible.builtin.include_vars:
        file: ../variables/install.yml
      delegate_to: localhost
    - name: Debug compose_dest
      ansible.builtin.debug:
        var: tailscale_auth_key
    - name: Update and upgrade packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
  roles:
    - role: install-docker
      when: docker is defined
    - role: install-nvidia
      when: nvidia is defined
    - role: install-tailscale
      when: tailscale is defined
    - role: gantsign.golang
      golang_version: "1.22.2"
      when: golang is defined
  tasks:
    - name: Add export PATH=$PATH:/opt/go/bin to .bashrc
      ansible.builtin.lineinfile:
        path: /home/mgarnier/.bashrc
        line: export PATH=$PATH:/opt/go/1.22.2/bin
        create: yes
        state: present
      when: golang is defined
