
- name: Reboot host
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
    msg: "Rebooting the system to apply changes"

- name: Restart docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true