name: home_assistant

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - /docker-data/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${ZEPHYR_HOME_ASSISTANT_PORT}:8123
    annotations:
      traefik-ports: ZEPHYR_HOME_ASSISTANT_PORT
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8123 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - type: volume
        source: fbx_docker_data
        target: /mosquitto/data
        volume:
          subpath: mosquitto/data
      - type: volume
        source: fbx_docker_data
        target: /mosquitto/config
        volume:
          subpath: mosquitto/config
    ports:
      - ${ZEPHYR_MOSQUITTO_1_PORT}:1883
      - ${ZEPHYR_MOSQUITTO_2_PORT}:9001
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "3",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
