version: "3.8"

services:
  autosaver:
    container_name: autosaver
    restart: unless-stopped
    image: mgarnier11/autosaver:1.0.11
    volumes:
      - bc_hetzner:/upload
      - bc_docker_data_fbx:/backups/docker-data-fbx
      # - bc_docker_data_notos:/backups/docker-data-notos
      - /docker-data:/backups/docker-data-boree
      # - ../../env:/backups/docker-data-boree/env
    ports:
      - ${BOREE_AUTOSAVER_PORT}:3000
    annotations:
      traefik-ports: BOREE_AUTOSAVER_PORT
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      UPLOAD_STRATEGY: CP
      ARCHIVE_STRATEGY: TAR

      ENABLE_RSYNC: true
      ENABLE_MAIL: true

      FOLDER_TO_BACKUP: /backups
      RSYNC_DEST_FOLDER: /rsync
      UPLOAD_DEST_FOLDER: /upload/backups

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SECURE: ${MAIL_SECURE}
      MAIL_LOGIN: ${MAIL_LOGIN}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      INFO_MAIL_TO: ${INFO_MAIL_TO}
      ERROR_MAIL_TO: ${ERROR_MAIL_TO}

      UPTOBOX_TOKEN: ${UPTOBOX_TOKEN}

      NTFY_SERVER: ${NTFY_SERVER}
      NTFY_TOPIC: ${NTFY_TOPIC}

      CRON_SCHEDULE: 15 4 * * *

      SMB_CONFIG: >
        {
          "hosts": [
            {
              "ip": "${ATHENA_PROXY_IP}",
              "user": "${SMB_USER}",
              "password": "${SMB_PWD}",
              "mountRoot": "/share",
              "mounts": [
                {
                  "dest": "/rsync",
                  "src": "/hdd-2/rsync"
                },
                {
                  "dest": "/backups/satisfactory/backups",
                  "src": "/ssd-1/satisfactory/backups"
                },
                {
                  "dest": "/backups/gonic-datas",
                  "src": "/ssd-1/gonic"
                },
                {
                  "dest": "/backups/jellyfin-config",
                  "src": "/ssd-1/jellyfin/config"
                },
                {
                  "dest": "/backups/palworld",
                  "src": "/ssd-1/palworld"
                },
                {
                  "dest": "/backups/satisfactory/saved",
                  "src": "/ssd-1/satisfactory/saved"
                },
                {
                  "dest": "/backups/nextcloud-datas",
                  "src": "/hdd-1/nextcloud"
                },
                {
                  "dest": "/backups/minecraft-maps/modded-1.19.2",
                  "src": "/ssd-1/minecraft/modded-1.19.2/server-world"
                },
                {
                  "dest": "/backups/paperless",
                  "src": "/hdd-1/paperless"
                }
              ]
            }
          ]
        }

x-default_opts: &default_opts
  type: cifs
  # device: //192.168.0.254/SSD1/docker-data
  o: "rw,username=${SMB_USER},password=${SMB_PWD},iocharset=utf8,uid=1000,sec=ntlmv2,file_mode=0777,dir_mode=0777"

volumes:
  bc_docker_data_fbx:
    name: bc_docker_data_fbx
    driver: local
    driver_opts:
      <<: *default_opts
      device: ${DOCKER_DATA}
  bc_docker_data_notos:
    name: bc_docker_data_notos
    driver: local
    driver_opts:
      <<: *default_opts
      device: //${NOTOS_IP}/share/docker-data
  bc_hetzner:
    name: bc_hetzner
    driver: local
    driver_opts:
      type: cifs
      device: ${HETZNER_DATA}
      o: "addr=${HETZNER_ADDR},username=${HETZNER_SMB_USER},password=${HETZNER_SMB_PWD},iocharset=utf8,uid=1000,sec=ntlmv2,file_mode=0777,dir_mode=0777"
