version: "3.8"

services:
  glances:
    extends:
      file: monitoring.yml
      service: glances

  dozzle:
    extends:
      file: monitoring.yml
      service: dozzle

  watchtower:
    extends:
      file: monitoring.yml
      service: watchtower

  dashy:
    container_name: dashy
    restart: unless-stopped
    image: mgarnier11/my-dashy
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    volumes:
      - dashy_config:/app/public
    ports:
      - 10002:80

  scrutiny_db:
    container_name: scrutiny_db
    restart: unless-stopped
    image: influxdb:latest
    # ports:
    #   - 8086:8086
    volumes:
      - scrutiny_db:/var/lib/influxdb2
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 20

  scrutiny_web:
    container_name: scrutiny_web
    restart: unless-stopped
    image: ghcr.io/analogj/scrutiny:master-web
    ports:
      - 10003:8080
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=scrutiny_db
    depends_on:
      - scrutiny_db
