version: "3.8"

services:
  glances:
    extends:
      file: monitoring.yml
      service: glances

  docker-socket-proxy:
    extends:
      file: monitoring.yml
      service: docker-socket-proxy

  dozzle:
    container_name: dozzle
    restart: unless-stopped
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_REMOTE_HOST=tcp://${HERMES_IP}:10001|Hermes,tcp://${APOLLON_IP}:10001|Apollon,tcp://${ATHENA_IP}:10001|Athena,tcp://${ARTEMIS_IP}:4201|Artemis
    ports:
      - 10002:8080

  watchtower:
    extends:
      file: monitoring.yml
      service: watchtower

  dashy:
    container_name: dashy
    restart: unless-stopped
    image: mgarnier11/my-dashy
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    volumes:
      - dashy_config:/app/public
    ports:
      - 10003:80

