services:
  nodesight:
    extends:
      file: monitoring.yml
      service: nodesight
    environment:
      HOSTNAME: ${BOREE_HOSTNAME}
      ENABLE_STATS_API: true
      STATS_API_URL: ${STATS_API_URL}
      SERVER_PORT: ${BOREE_NODESIGHT_PORT}
    annotations:
      traefik-ports: BOREE_NODESIGHT_PORT
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:${BOREE_NODESIGHT_PORT} || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dozzle:
    extends:
      file: monitoring.yml
      service: dozzle
    ports:
      - ${BOREE_DOZZLE_PORT}:8080
    annotations:
      traefik-ports: BOREE_DOZZLE_PORT

  watchtower:
    extends:
      file: monitoring.yml
      service: watchtower

  dashboard:
    container_name: dashboard
    restart: unless-stopped
    image: mgarnier11/dashboard:latest
    environment:
      APP_CONF_PATH: /config/conf.yml
      ICONS_PATH: /config/icons
    volumes:
      - dashboard_config:/config
    ports:
      - ${BOREE_DASHBOARD_PORT}:3000
    annotations:
      traefik-ports: BOREE_DASHBOARD_PORT

  stats-api:
    container_name: stats-api
    restart: unless-stopped
    image: mgarnier11/stats-api:latest
    environment:
      DB_HOST: ${INFLUXDB_HOST}
      DB_ORG: ${INFLUXDB_ORG}
      DB_BUCKET: home-test
      DB_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - ${BOREE_STATS_API_PORT}:3000
    annotations:
      traefik-ports: BOREE_STATS_API_PORT
