version: "3.8"

services:
  nodesight:
    extends:
      file: monitoring.yml
      service: nodesight
    environment:
      HOSTNAME: ${EUROS_HOSTNAME}
      ENABLE_STATS_API: true
      STATS_API_URL: ${STATS_API_URL}
      SERVER_PORT: ${EUROS_NODESIGHT_PORT}
    # ports:
    #   - ${EUROS_NODESIGHT_PORT}:3000
    annotations:
      traefik-ports: EUROS_NODESIGHT_PORT

  dozzle:
    extends:
      file: monitoring.yml
      service: dozzle
    ports:
      - ${EUROS_DOZZLE_PORT}:8080
    annotations:
      traefik-ports: EUROS_DOZZLE_PORT

  watchtower:
    extends:
      file: monitoring.yml
      service: watchtower

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    environment:
      - TZ=${TZ}
    ports:
      - ${EUROS_NTFY_PORT}:80
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_data:/etc/ntfy
    annotations:
      traefik-ports: EUROS_NTFY_PORT