version: "3.8"

services:
  glances:
    container_name: glances
    restart: unless-stopped
    image: nicolargo/glances:ubuntu-latest-full
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-d -t 1 -w
      - NVIDIA_VISIBLE_DEVICES=all

  dozzle:
    container_name: dozzle
    restart: unless-stopped
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - WATCHTOWER_POLL_INTERVAL=900
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=email
      # - WATCHTOWER_NOTIFICATION_URL=ntfy://${NTFY_SERVER}/${NTFY_TOPIC}?title=Watchtower
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${MAIL_LOGIN}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${INFO_MAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${MAIL_LOGIN}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${MAIL_PASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${MAIL_HOST}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${MAIL_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nodesight:
    image: mgarnier11/nodesight:latest
    container_name: nodesight
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /:/mnt/host:ro
