- name: Check if docker is installed
  become: true
  ansible.builtin.command: docker --version
  register: docker_version
  ignore_errors: true
  changed_when: true

- name: Install Docker
  when: docker_version.rc != 0
  block:
    - name: Get installation script
      become: true
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"

    - name: Install docker
      become: true
      ansible.builtin.command: /tmp/get-docker.sh
      changed_when: true

    - name: Add user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

- name: Add the psFormat to config.json
  block:
    - name: Create the .docker directory
      ansible.builtin.file:
        path: /home/mgarnier/.docker
        state: directory
        mode: "0755"

    - name: Create the config.json file
      ansible.builtin.copy:
        dest: /home/mgarnier/.docker/config.json
        mode: "0644"
        content: |
          {
          {% raw %}"psFormat": "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.RunningFor}}\t"{% endraw %}
          }

- name: Add dns to daemon.json
  become: true
  block:
    - name: Create the .docker directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: Create the daemon.json file
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        mode: "0644"
        content: |
          {
          {% raw %}"dns": ["100.100.100.100"]{% endraw %}
          }

- name: Start docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
