version: "3.8"

services:
  plex:
    container_name: plex
    restart: unless-stopped
    image: lscr.io/linuxserver/plex:latest
    runtime: nvidia
    ports:
      - ${ATHENA_PLEX_PORT}:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - ADVERTISE_IP="https://${PLEX_URL}:443"
      - NVIDIA_VISIBLE_DEVICES=all
      # - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /ssd-1/plex/config:/config
      - /big-hdd/plex:/data
